$col = "#|TIMESTAMP|ORDER_ID|VERSION|BACK_OFFICE_NOTE_ID|CONTRACTING_BOOK_CODE|COUNTERPARTY_CODE|COUNTERPARTY_TYPE|COUNTERPARTY_TYPE_QUALIFIER|DEALT_CURRENCY_ID|ENTERED_BY|EXECUTING_BOOK_CODE|GIVEUP_COUNTERPARTY_CODE|INSTRUMENT_CODE|MARKET_ID|ORDER_NOTE_ID|ORIGINATING_ENTITY_ID|PRIMARY_SALES_TRADER|PRIMARY_TRADER|ROOT_ORDER_ID|REPRESENTATIVE_ID|SETTLEMENT_CURRENCY_ID|BID_PRICE|BROKERAGE_RULE_ID|BROKERAGE_CALC_ARGUMENT|BROKERAGE_CALC_METHOD|BUY_SELL|BUY_SELL_SENSE|BUY_SELL_QUALIFIER|RETAIL_ACCOUNT_NUMBER|CLASSIFICATION|CLIENT_GROSS_BASIS|COMMISSION_RULE_ID|COMMISSION_CALC_ARGUMENT|COMMISSION_CALC_METHOD|COMMISSION_VALUE|COUNTERPARTY_CLEARING_CODE|DEALING_CAPACITY|DEALING_CAPACITY_QUALIFIER|DEALING_INSTRUCTIONS|DEFAULT_CPTY_ACCOUNT_ID|DEFERRED_DATE|DISPLAY_QUANTITY|ENTERED_DATETIME|EXPIRY_DATETIME|EXPIRY_TIMEZONE|EXPIRY_TYPE|INSTRUCTION_SELECTOR|INSTRUMENT_TO_DEALT_RATE|INSTRUMENT_TO_DEALT_SENSE|IS_DISCRETIONARY|IS_MARGIN|LAST_TRADE_PRICE|LIMIT_PRICE|MARKUP_RULE_ID|MARKUP_CALC_ARGUMENT|MARKUP_CALC_METHOD|MINIMUM_QUANTITY|OFFER_PRICE|ORDER_DATETIME|ORDER_ENTRY_TYPE|ORDER_FLAGS|ORDER_PRICE_TYPE|ORDER_PRICE_TYPE_QUALIFIER|ROUTING_BRANCH_CODE|SALES_CREDIT_RULE_ID|SALES_CREDIT_CALC_ARGUMENT|SALES_CREDIT_CALC_METHOD|SETTLEMENT_DAYS|USER_DISCRETION|DEALT_TO_SETTLEMENT_RATE|DEALT_TO_SETTLEMENT_SENSE|STOP_PRICE|TOTAL_QUANTITY|TRADING_QUANTITY|TRADING_PERIOD|VALUE_DATE|GLOBAL_ORDER|ENTRY_LOCATION_ID|ROUTED_ORDER_CODE|ORDER_WEIGHT|MARGIN_APPROVAL|BENCHMARK|SHORT_SELL_GROUP_ID|IS_CFD|LOCATE_REQUIRED|FOREX_REQUIRED|CUST_XP_DATA_0|CUST_XP_DATA_1|CUST_XP_DATA_2|CUST_XP_DATA_3|CUST_XP_DATA_4|CUST_XP_DATA_5|CUST_XP_DATA_6|CUST_XP_DATA_7|CUST_XP_DATA_8|CUST_XP_DATA_9|CUST_XP_DATA_10|CUST_XP_DATA_11|CUST_XP_DATA_12|PARENT_ORDER_ID|SETTLEMENT_DATE|CUSTOMER_IDENTIFICATION|TRADER_NOTE|CONTRACT_SIZE|EXPIRY_DATE|STRIKE_PRICE|OPTION_TYPE|OPRA_CODE|ORDER_NOTE|PRIMARY_STATE|COMPLETION_REASON|CUST_ACCOUNT_ID|CUST_CONSENT_CODE|SENDER_SUB_ID|CURRENT_ENTITY_ID|EXCHANGE_TRADING_CAPACITY|ORDER_AVERAGE_PRICE|ORDER_ORIGINATOR_TYPE|ORDER_ORIGINATOR_CODE|NUM_OF_EXECUTIONS|LIMIT_PRICE_WITHOUT_COMMISSION|NET_ORDER_AVERAGE_PRICE|ON_BEHALF_OF_SUB_ID|QUANTITY_FILLED|LAST_ROUTING_RULE|LAST_SERVICE_ID|LAST_ROUTING_RULE_NAME|LAST_TRADER|OPEN_CLOSE|BACK_OFFICE_NOTE"
$headers = $col.split("|").Replace(" ", "")
$result = @()
$files = Get-ChildItem -Path "C:\Users\username\Documents\Crap\"
foreach ($file in $files){
    
    $lines = Get-Content $file.FullName
    foreach($line in $lines){
        if ($line -like "*TIMESTAMP*"){
            continue
        }
        #if ($line -notlike "*BEAUF*"){
        #    continue        }
        $line = $line.split("|")
        $row = New-Object psobject
        $i = 0
        foreach ($header in $headers){
            $row | Add-Member NoteProperty -Name $header -Value $line[$i]
            $i++
        }
        #$row
        $result += $row
       
    }
    

}

$result | Export-Csv C:\Users\Username\Export.csv